### ISSUE TITLE
DO NOT abandon project!!!! 

### ISSUE THREAD

**Issue by Trusiak** [Alchemist0823/three.quarks#77]
@Alchemist0823 DO NOT ABANDON PROJECT.

it has really enormous potential, and I see that you have abandoned work on it for 4 months...

**Comment by Alchemist0823** [comment]
Thanks for your encouragement. I have a very busy day job right now.
You can request what kind of features you want here or discord.
You can make contribution too. It's a community project at the end of the day.

If you want to help me, you can consider getting a membership on quarks.art.

**Comment by Trusiak** [comment]
@Alchemist0823 The library needs development. It needs documentation, it needs tutorials etc. Of course I would like to help, but without documentation it is extremely difficult.

**Comment by hichemfantar** [comment]
I agree! the only potential issue with adoption is the unclear license.
many people will avoid quarks simply due to the fear of the license coming back to bite them in the a$$
an MIT license would do wonders for project adoption, you see great projects like threejs and r3f that wouldn't be where they are today if they didn't use a permissive software license.
reason is no one wants to contribute to a project that could become limiting suddenly, look at redis, elastic search, etc

**Comment by Alchemist0823** [comment]
Hi @hichemfantar, thank you for contributing your opinions and ideas. 

The popularity of a project is ultimately determined by how good the product is, and how many people the project can serve and how big the market is. Right now, the license is not the biggest blocker. three.quarks is under MIT license, no doubt. We could make this much clearer on the project website.

There are many reasons the cloud editor is not open-sourced. I can list a few here:

- The customers we serve are designers and artists. They are not necessarily developers who can contribute to the code.
- External maintained editor enables multiplayer collaboration, reduces the hosting and infrastructure maintenance cost of our users.
- Quarks VFX would provide AI model to enhance the capability of the editor. it's not easy and affordable to run for most our customers.

**Comment by hichemfantar** [comment]
@Alchemist0823 thanks for the reply.
You can add a license file in the repo to make it clear. Example: https://github.com/hichemfantar/hdri-to-cubemap-converter/blob/main/LICENSE.txt

Actually If the editor is open source then you can get many hosting and devops services for free as there’s pretty much endless support for open source projects.

I’m also willing to work on making the editor a great experience since I have years of experience with full stack development.

In the end, I understand your decision and I’m simply trying to brainstorm other ways to approach the project.

**Comment by BeardScript** [comment]
Hey @Alchemist0823 thanks for building this. I'm currently making a free plugin for rogueengine.io for three.quarks. It's definitely super challenging with barely any documentation, I'm really struggling but hopefully this plugin will bring some attention to the library from my end.

Please don't give up. You've got something awesome here which has the potential to be the standard way to do particles on the web.

I only make integrations for libraries that I'm bullish about and I'm definitely bullish about quarks. Hopefully we can collaborate in the future to keep improving the 3D web landscape. As I get better acquainted with Quarks I'll be happy to do some contributions, at least from the docs side.

The plugin will be open-source, I'll let you know when the repo is published in case you'd like to check it out.

Happy hacking mate, let's keep at it!
